### ISSUE TITLE
[WORK] WORK2

### ISSUE THREAD

**Issue by tikitorchey** [tiki-torches/GenerativeArtWorks#7]
## Acceptance Criteria
- [ ] criteria 1
- [ ] criteria 2
- [ ] criteria 3

## Proposed Method
- method 1
- method 2
- method 3

## Reference
- reference1
- reference2
- reference3

**Comment by tikitorchey** [comment]
https://user-images.githubusercontent.com/122960484/228438252-3e0338cc-0af0-4525-aba1-f7e933add418.mp4

**Comment by tiki-torches** [comment]
https://user-images.githubusercontent.com/122960484/228444225-98813f70-5aad-4e47-ac2e-b592ff78ceea.mp4

**Comment by tikitorchey** [comment]
https://user-images.githubusercontent.com/122960484/228451575-c4d55aa0-0753-4c66-aeda-d4f6b27c33ab.mp4

**Comment by tikitorchey** [comment]
[Playerが持つアニメーションIDを作品内のロジックで利用できるように変更](https://github.com/tiki-torches/GenerativeArtWorks/commit/7d047b5913ed8702b4f598b03482b755e3a08766)

時間管理を実時間ベースで行う場合（Dateから生成した数値でランダムな値を使用している場合など）、一時停止と再始動を実行したときに突然大幅な変化が発生することがある。連続性が壊れる。

対策としてアニメーションIDを時間管理に用いることに。

**Comment by tikitorchey** [comment]
Uploading Document - Google Chrome 2023-03-30 11-14-08.mp4…
